version: '3.8'

services:
  backend:
    container_name: cod-mon-api
    image: 'cod-mon-backend:1.1.1'
    build:
      context: ./back_end
    ports:
      - 80:80
  frontend:
    container_name: cod-mon
    image: 'cod-mon-frontend:1.1.1'
    build:
      context: ./front_end
    ports:
      - 80:80
