version: '3.8'

services:
  backend:
    container_name: 'cod-mon-be'
    image: 'ghcr.io/lnls-sirius/cod-mon-backend:1.0.0'
    build:
      context: ./back_end
    ports:
      - 8080:8080
  frontend:
    container_name: 'cod-mon-fe'
    image: 'ghcr.io/lnls-sirius/cod-mon-frontend:1.0.0'
    build:
      context: ./front_end
    ports:
      - 80:80
