name: COD Monitor CD

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
      - name: Run Docker Compose 🐳
        run: docker-compose build
