name: COD Monitor CD

on:
  push:
    branches: main

defaults:
  run:
    working-directory: .

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: list
        run: ls
      - name: Run Docker Compose 🐳
        run: docker-compose build
