name: COD Monitor CD

on:
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Build Docker Compose 🏗️
        run: docker-compose build

      - name: Login to GitHub Container Registry 🔓
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Docker Compose 🪖
        run: docker-compose push
