name: COD Monitor CD

on:
  pull_request:
    branches: main

defaults:
  run:
    working-directory: .

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Print working directory
        run: pwd
      - name: Run Docker Compose 🐳
        run: docker-compose build
